# Dataset analysis
In here I'll show what kind of choices I have made during feature selection for the model.

#### Lets load in all imports, and the pruned data set ( for loading time. )

In [11]:
#Imports for analysis
import os
import json
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#Import the dataset (takes a few minutes, and requires more RAM the more chunksize)
#Costs 4 gb of ram with these settings.
counter = 3 

for chunk in pd.read_csv('base_experiment.csv',low_memory=False, chunksize=300000):
    if counter < 1 :
        break
    # do things with chunk
    elif counter == 3:
        df = chunk.copy()
        counter += -1
        print("Setup dataset")
    else:
        df.append(chunk)
        print("Added dataset: ",counter)
        counter += -1
print("loaded part of csv.")

Setup dataset
loaded part of csv.

In [12]:
df.describe()

,Unnamed: 0,label,strings.numstrings,strings.avlength,strings.printables,strings.entropy,strings.paths,strings.urls,strings.registry,strings.MZ,...,header.optional.minor_image_version,header.optional.major_linker_version,header.optional.minor_linker_version,header.optional.major_operating_system_version,header.optional.minor_operating_system_version,header.optional.major_subsystem_version,header.optional.minor_subsystem_version,header.optional.sizeof_code,header.optional.sizeof_headers,header.optional.sizeof_heap_commit
count,132182.000000,132182.000000,1.321820e+05,132182.000000,1.321820e+05,132182.000000,132182.000000,132182.000000,132182.000000,132182.000000,...,132182.000000,132182.000000,132182.000000,132182.000000,132182.000000,132182.000000,132182.000000,1.321820e+05,1.321820e+05,1.321820e+05
mean,66090.500000,0.098932,6.735129e+03,33.649511,9.672806e+04,5.689114,2.341627,16.010115,0.528604,15.968074,...,14.850131,10.503019,7.027485,4.843504,0.323698,4.731370,0.356123,8.190877e+05,1.693076e+03,3.781069e+04
std,38157.800978,0.789814,2.712004e+04,624.818839,4.643024e+05,0.732426,171.648999,96.571754,19.551151,91.397580,...,615.217076,10.595197,13.283272,5.475644,5.498788,1.088699,16.941260,2.589530e+07,2.479534e+04,5.227358e+06
min,0.000000,-1.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,33045.250000,-1.000000,3.690000e+02,8.797218,5.303000e+03,5.349022,0.000000,0.000000,0.000000,1.000000,...,0.000000,6.000000,0.000000,4.000000,0.000000,4.000000,0.000000,1.280000e+04,1.024000e+03,4.096000e+03
50%,66090.500000,0.000000,1.479000e+03,12.980626,1.912150e+04,5.795223,0.000000,0.000000,0.000000,4.000000,...,0.000000,9.000000,0.000000,4.000000,0.000000,5.000000,0.000000,7.475200e+04,1.024000e+03,4.096000e+03
75%,99135.750000,1.000000,4.866750e+03,18.627952,6.071425e+04,6.190537,1.000000,12.000000,0.000000,9.000000,...,0.000000,12.000000,11.000000,5.000000,0.000000,5.000000,0.000000,3.717120e+05,1.024000e+03,4.096000e+03
max,132181.000000,1.000000,2.483308e+06,90970.282353,5.322966e+07,6.584957,56442.000000,9409.000000,2492.000000,8196.000000,...,65535.000000,255.000000,255.000000,1593.000000,1598.000000,10.000000,4352.000000,4.294844e+09,6.029312e+06,1.235176e+09

##### As you can see in the above table seem not used alot. Like for example:
strings.entropy, strings.paths, strings.urls, strings.registry

To identify this we want to count all null values per column:

In [13]:
df.isnull().sum()

Unnamed: 0                                            0
sha256                                                0
md5                                                   0
appeared                                              0
label                                                 0
avclass                                           70422
histogram                                             0
byteentropy                                           0
exports                                               0
datadirectories                                       0
strings.numstrings                                    0
strings.avlength                                      0
strings.printabledist                                 0
strings.printables                                    0
strings.entropy                                       0
strings.paths                                         0
strings.urls                                          0
strings.registry                                      0
strings.MZ                                            0
general.size                                          0
general.vsize                                         0
general.has_debug                                     0
general.exports                                       0
general.has_relocations                               0
general.has_resources                                 0
general.has_signature                                 0
general.has_tls                                       0
general.symbols                                       0
header.coff.timestamp                                 0
header.coff.machine                                   0
header.coff.characteristics                           0
header.optional.subsystem                             0
header.optional.dll_characteristics                   0
header.optional.magic                                 0
header.optional.major_image_version                   0
header.optional.minor_image_version                   0
header.optional.major_linker_version                  0
header.optional.minor_linker_version                  0
header.optional.major_operating_system_version        0
header.optional.minor_operating_system_version        0
header.optional.major_subsystem_version               0
header.optional.minor_subsystem_version               0
header.optional.sizeof_code                           0
header.optional.sizeof_headers                        0
header.optional.sizeof_heap_commit                    0
section.entry                                     11659
section.sections                                      0
dtype: int64

This indicates that the assumption that was made was wrong, and only the section entry is actually not used in all cases.
Label 0 means that it is a benign sample, so this could also overfit the model since this is the actual answer if a file is malicious or not. So label could be removed, and section entry should be checked if this should be removed or not. 
Same counts for av-class. We will do this in a later notebook

In [14]:
df.sort_values("label",ascending = False).head(2)

,Unnamed: 0,sha256,md5,appeared,label,avclass,histogram,byteentropy,exports,datadirectories,...,header.optional.minor_linker_version,header.optional.major_operating_system_version,header.optional.minor_operating_system_version,header.optional.major_subsystem_version,header.optional.minor_subsystem_version,header.optional.sizeof_code,header.optional.sizeof_headers,header.optional.sizeof_heap_commit,section.entry,section.sections
66091,66091,5ca37e443bd14bf152cde39ef393166f494e9bf66d382f...,24f33ca7dd8d8b0ad4365d26ef2416af,2018-07,1,agentb,"[1813, 231, 147, 187, 222, 159, 145, 182, 198,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",[],"[{'name': 'EXPORT_TABLE', 'size': 0, 'virtual_...",...,25,4,0,4,0,24576,4096,4096,UPX0,"[{'name': 'UPX0', 'size': 0, 'entropy': -0.0, ..."
65888,65888,86bde8cdfbb93b89b494e3ab2d560c49dc576fe21d5f42...,a1833b1713d89b066f69f5649c8b43f1,2018-07,1,fareit,"[96506, 9299, 3638, 3560, 7212, 3586, 4129, 34...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",[],"[{'name': 'EXPORT_TABLE', 'size': 0, 'virtual_...",...,25,4,0,4,0,443392,1024,4096,CODE,"[{'name': 'CODE', 'size': 443392, 'entropy': 6..."

The 4th data set has a relatively balanced data set, but has some other parts that need to be pruned.
Because of this we will clean it up a bit more.

In [15]:
#drop avclass labels now.
df.drop(list(df.filter(regex = 'imports*')), axis = 1, inplace = True)

In [16]:

print("df has this amount of malicious:",sum(df['label'] == 1))
print("df has this amount of benign:",sum(df['label'] == 0))
print("df has this amount of unclassified:",sum(df['label'] == -1))

df has this amount of malicious: 48413
df has this amount of benign: 48433
df has this amount of unclassified: 35336

Because we cant use the unclassified data set for actual models we remove this.

In [9]:
df = df[df['label'] != -1]
print("df has this amount of unclassified:",sum(df['label'] == -1))
print("df has this amount of malicious:",sum(df['label'] == 1))
#now also 50-50 balance the data set. ( in a actual usecase you might want to use bigger data sets
#And also maby change the balance to a more representative Positive:negative ratio )
remove_n = sum(df['label'] == 1) - sum(df['label'] == 0)
index_to_drop = df.index[df['label'] == 1][:remove_n]
#Finally drop those indexes
df = df.drop(index_to_drop)
print("after balancing:")
print("df has this amount of unclassified:",sum(df['label'] == -1))
print("df has this amount of malicious:",sum(df['label'] == 1))
print("df has this amount of benign:",sum(df['label'] == 0))

df has this amount of unclassified: 0
df has this amount of malicious: 48413
after balancing:
df has this amount of unclassified: 0
df has this amount of malicious: 20
df has this amount of benign: 48433

In [10]:
df.co

AttributeError: 'DataFrame' object has no attribute 'co'

In [19]:
df = df[df['label'] != -1]
df.to_csv("100kbalanced.csv")